### ISSUE TITLE
Provide manifests for declarative deployments

### ISSUE THREAD

**Issue by thomassandslyst** [stepro/kdo#43]
Hello!

This tool is a game changer! I'd really like to get it further integrated into our systems but currently the only way to install the server-side component is via the `--install` option.

Is it possible to provide either the raw manifests or a helm chart along with each release?

**Comment by stepro** [comment]
Thanks @thomassandslyst for the vote of confidence!

I'd be happy to provide the manifest in a form that works for you. In the immediate term, you can find it in the `pkg/server/server.go` source file as a constant `manifest` value. You can simply copy this value to a `kdo-server.yaml` file and install it by running `kubectl apply -n kube-system -f kdo-server.yaml`, or add the manifest file to an existing Helm chart. The one thing the `kdo --install` command also does is wait for the server components to be ready. It's possible that as a Helm chart, `helm install` knows how to wait appropriately for all instances of the daemon set to be ready, but I haven't explored that. I don't think just running `kubectl apply` knows how to wait.

What format would be most appropriate for you? Also, I'd love to understand how you are using kdo as a means to figuring out where I should take it next. Thanks!

**Comment by stepro** [comment]
Let me know @thomassandslyst if you're satisfied with the solution I provided or you would like me to do more. Or if you've since discovered another tool that better suits your needs, I'd love to hear how it's been more effective for your workflows.

**Comment by stepro** [comment]
I'm going to close this issue for now, but feel free to re-open if you'd like to engage further.
