### ISSUE TITLE
Is it possible (or will be) to use containerd based cluster?

### ISSUE THREAD

**Issue by schibrikov** [stepro/kdo#67]
Hi!
This project looks really promising to me as it seems to allow to quickly use cluster resources (e.g. gpu-enabled machines) in development.

I'm using Azure-hosted managed cluster which as it seems using containerd runtime instead of docker.
Am I correct that it's impossible to use such a cluster with this project?

If I'm right the question is - is it possible in theory and has chances to be implemented?

**Comment by stepro** [comment]
Great question! Most features of kdo continue to work irrespective of the underlying container runtime. However, you will not be able to ask kdo to build an image on-demand in the cluster if using a runtime-only container execution environment like containerd. The specific requirements are covered in the documentation [here](https://github.com/stepro/kdo#build-flags).

The workaround for now would be to build your image manually and push it to a container registry that is visible to the cluster. Then, you can ask kdo to run that image. Depending on how fancy you want to get, you *could* configure things such that you are running a standard base image in the cluster, and then use kdo's file synchronization capabilities to push code into that container and receive updates when local files change. When combined with running build commands for your app in the image itself, this could simulate the building of an image in the cluster quite well.

I had previously looked into systems for building images inside of containers, but it has been a while. Just poking around, it looks like there may be another option now through buildx that comes with [specific support](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#kubernetes-driver) for Kubernetes. I'll take a look at what it would mean to switch to that.

Hope this helps!

**Comment by schibrikov** [comment]
Thanks for great response!

In my case I'm also using M1-based MacBook, so sometimes I'm unable to build image locally and use it in my cluster due to arch difference. I also have cases when the image built is really huge (like 20GB) and it's hard to transfer it registry from my location.
With this in mind kdo could give me superpowers (in comparison) with its single-command builds right in the cluster and then getting straight into shell.

Just wondering -- could it be possible to run docker image inside containerd to build image?

**Comment by stepro** [comment]
Those are great scenarios. I will look into running buildx in Kubernetes and let you know how feasible that looks.

**Comment by stepro** [comment]
I finally got around to this - see #69.
